server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:awesomebankdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:mockData.sql

logging:
  level:
    org.apache.catalina: OFF
    org.apache.coyote: OFF
    org.apache.tomcat: OFF
    org.springframework.web.servlet.DispatcherServlet: OFF
